### ISSUE TITLE
1.0.0 Release

### ISSUE THREAD

**Issue by kuuurt13** [kuuurt13/ng-block-ui#41]
## 1.0.0 Release
I feel like this library has reach a good degree of stability over the past few months and I would like to push forward with a `1.0.0` release. This issue is to track of all the planned changes/tasks I would like finish before I officially release `1.0.0`. 

Also, `1.0.0` will mark the end of Angular 2.x support. Angular 4.x had many breaking changes from 2.x and because of this I had to support each version separately. Since Angular 5 has been released and Angular 4.0 has been out for a few months I think it is reasonable that this library will target Angular 4.0 and up going forward.

Please feel free to use this issue for questions or concerns with the planned `1.0.0` release. Everyone's input is always welcome :smiley: 

### Chores:
- [x] Create `1.0.0 Release` label
- [x] Improve developer experience to encourage more PRs from other contributors
- [x] Create a CONTRIBUTING.md
- [x] Create 1.0.0 migration guide
- [x] Increase tests

### Clean Up / Refactor
- [x] Introduce module to include `forRoot` method setting app wide settings
- [x] Clean up docs to address frequently asked questions

### New Features
- [x] Automatic blocking for http requests #38 
- [x] Prevent browser navigation for all http request #39 
- [x] Expose a way to check if block ui is currently active #40

**Comment by kuuurt13** [comment]
1.0.0 has been released :tada:
